### ISSUE TITLE
Vary Git Commit Requirements by Phase

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#376]
## Overview
The code required for each phase really is quite different, and it would make a lot sense to vary the requirements to match this. Specifically, the earliest phases do not really require 10 commits as they can be finished with 8 reasonably sized commits. TA's in the 2024 spring semester estimate that about 10% of students were flagged for having 8-9 commits even though the student's had a done a thorough job on the assignment. Those students received full credit.

Note that students receive essentially a free commit when they originally create their GitHub repo which create a commit. Usually, this occurs much earlier in the semester.

## Current Schedule
Currently require **10 commits** spaced over **3 days**, each with at least **5 line changes** for **all phases**.

## Proposed Schedule
The following table proposes a requirement schedule for all of the phases. While we could vary the number for each phase, I think it makes sense to break it into an intro period with lower requirements, a phase without any code, and then the implementation period with higher requirements. These requirements aren't designed to actually be difficult and all students should be easily meeting these requirements just by committing at reasonable checkpoints.

| Phase | Commits | Days | Line Changes |
|--------|--------|--------|--------|
| 0 | 8 | 2 | 5 |
| 1 | 8 | 2 | 5 |
| 3 | 12 | 3 | 5 |
| 4 | 12 | 3 | 5 |
| 5 | 12 | 3 | 5 | 
| 6 | 12 | 3 | 5 | 

Notice the increase in the line-change requirements. 20 line changes can be viewed as 10 lines modified (insertions + deletions), and I think it's OK to encourage students to write substantial commits rather than committing every single time they change any line.

This proposal is not final, and should be edited to reflect any agreed upon requirements.

## Todo
- [ ] Agree on a requirement schedule
- [ ] Add support for configuring these values based on the phase
- [ ] Update the phase spec grading tables to show the requirements
    - [ ] [Phase 0](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/0-chess-moves/chess-moves.md#grading-rubric)
    - [ ] [Phase 1](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/1-chess-game/chess-game.md#grading-rubric)
    - [ ] [Phase 3](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/3-web-api/web-api.md#grading-rubric)
    - [ ] [Phase 4](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/4-database/database.md#grading-rubric)
    - [ ] [Phase 5](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/4-database/database.md#grading-rubric)
    - [ ] [Phase 6](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/6-gameplay/gameplay.md#grading-rubric)

## Credit
Thanks to @jerodw for leading the discussion on this topic. Thanks to @19mdavenport, @prattnj, @mewilker for adding perspective and thoughts on the issue.

@rodham You'll want to be aware of this issue for Summer 2024 😉

**Comment by jerodw** [comment]
James, I don't want to increase the line change requirement above 5. I
think that sends the wrong message (that commits should contain a lot of
code--I think more commits of fewer lines are better).

**Comment by frozenfrank** [comment]
@jerodw Thanks for the input. I've updated the proposal to set all the line change limits to 5. What do you think about the rest of it?

**Comment by jerodw** [comment]
Looks good to me
