### ISSUE TITLE
Backend: AutoGrader rejects submissions without the previous head commit without grading

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/autograder#420]
## Overview
Too many students are running into project setup issues, and nuking their existing Git repository just to replace it with another one. This seems fine, except that the AutoGrader assumes that their previous commit history is available in order to grade the new commits. (It could be available, but students end up deleting the previous history which really isn't best practice.)

I tried having the student resubmit the GitHub phase (to produce a reference to a valid Git object), but the AutoGrader doesn't seem to be using it. Or, if it is, it's still getting caught up by the missing object reference.

The result is a failure message reported to the student and a refusal to continue grading. This means that no manual submission entry exists in the database to approve.
> Failed to verify commits: Missing commit OLD_COMMIT_HASH
> — src/main/java/edu/byu/cs/autograder/git/GitHelper.java:150

## Complexity
The Commit Verifier is specifically expecting to find the previous commit hash in the repository so that we can grade only the new commits. 

## Proposal
In the event that some commits cannot be found, we should generate a warning on Phase 0, and on future phases, continue the grading but fail the verification so that a TA can approve the submission.

Reviewed with @19mdavenport 

## TODO
- [ ] Provide counts of the number of commits that would be affected in each warning message
- [ ] Determine if we should properly re-evaluate all of the remaining commits after some are removed (significant commits, days with commits)
- [ ] Send warnings to Observer with `sendWarning()`
- [ ] Test that the data structures are behaving the way we expect them to

**Comment by frozenfrank** [comment]
For the record, here is a stack trace showing the error caused by this issue:

```js
{
  "timestamp_ms": 1726440032360,
  "class": "edu.byu.cs.autograder.git.GitHelper",
  "level": "ERROR",
  "message": "Failed to verify commits",
  "stack_trace": `org.eclipse.jgit.errors.MissingObjectException: Missing commit 68c42b91ffee7650da49aa07d68814acc1606ff7
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:138)
    at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:1188)
    at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:149)
    at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:349)
    at org.eclipse.jgit.revwalk.RevWalk.markUninteresting(RevWalk.java:418)
    at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:344)
    at org.eclipse.jgit.api.LogCommand.not(LogCommand.java:209)
    at org.eclipse.jgit.api.LogCommand.addRange(LogCommand.java:242)
    at edu.byu.cs.analytics.CommitAnalytics.getCommitsBetweenBounds(CommitAnalytics.java:207)
    at edu.byu.cs.analytics.CommitAnalytics.countCommitsByDay(CommitAnalytics.java:64)
    at edu.byu.cs.autograder.git.GitHelper.verifyRegularCommits(GitHelper.java:203)
    at edu.byu.cs.autograder.git.GitHelper.verifyCommitRequirements(GitHelper.java:145)
    at edu.byu.cs.autograder.git.GitHelper.verifyCommitHistory(GitHelper.java:65)
    at edu.byu.cs.autograder.git.GitHelper.setUpAndVerifyHistory(GitHelper.java:47)
    at edu.byu.cs.autograder.Grader.run(Grader.java:89)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
  `
}
```
